src/Presentation/BiletAPI.WebUI/Models/ErrorViewModel.cs
namespace BiletAPI.WebUI.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

src/Presentation/BiletAPI.WebUI/Controllers/CityController.cs
using BiletAPI.Application.Models.Dtos.LoginDtos;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using System;
using BiletAPI.Application.Models.Dtos.CityDto;
using System.Net.Http;


namespace BiletAPI.WebUI.Controllers
{
	public class CityController : Controller
	{
		private readonly HttpClient _httpClient;
		private readonly string _baseUrl;

		public CityController(HttpClient httpClient)
		{
			_httpClient = httpClient;
			_baseUrl = "https://localhost:7270/api";
		}
		[HttpGet]
		public IActionResult AddCity()
		{
			return View();
		}
		//[HttpPost]
		//public async Task<IActionResult> AddCity(CityDto model)
		//{
		//	using (var httpClient = new HttpClient())
		//	{
		//		StringContent content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json"); //Türkçe karakterini destekleyen json oluşturduk.

		//		using (var cevap = await httpClient.PostAsync($"{_baseUrl}/City/AddCity", content))
		//		{
		//			string apiCevap = await cevap.Content.ReadAsStringAsync();
		//		}
		//	}
		//	return RedirectToAction("Index", "HomePage");
		//}
		[HttpPost]
		public async Task<IActionResult> AddCity(CityDto model)
		{
			if (ModelState.IsValid)
			{
				var content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");

				using var response = await _httpClient.PostAsync($"{_baseUrl}/City/AddCity/AddCity", content);

				if (response.IsSuccessStatusCode)
				{
					return RedirectToAction("Index", "HomePage");
				}
				else
				{
					ModelState.AddModelError("", "Registration failed");
				}
			}

			return View(model);
		}
	}
}

src/Presentation/BiletAPI.WebUI/Controllers/HomePageController.cs
using Microsoft.AspNetCore.Mvc;

namespace BiletAPI.WebUI.Controllers
{
	public class HomePageController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

src/Presentation/BiletAPI.WebUI/Controllers/LoginController.cs
using BiletAPI.Application.Service.UserServices;
using BiletAPI.Domain.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using System;
using Microsoft.AspNetCore.Authorization;
using BiletAPI.API.Model;
using System.Security.Claims;
using BiletAPI.Application.Models.Dtos.LoginDtos;
using System.Net.Http;

namespace BiletAPI.WebUI.Controllers
{

	public class LoginController : Controller
	{
		private readonly HttpClient _httpClient;
		private readonly string _baseUrl;

		public LoginController(HttpClient httpClient)
		{
			_httpClient = httpClient;     
			_baseUrl = "https://localhost:7270/api";
		}
		[HttpGet]
		public IActionResult Login()
		{
			return View();
		}
		[HttpPost]
		public async Task<IActionResult> Login(LoginDto model)
		{

			if (ModelState.IsValid)
			{
				var content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");

				using var response = await _httpClient.PostAsync($"{_baseUrl}/User/Login/Login", content);

				if (response.IsSuccessStatusCode)
				{
					// Do something on success, e.g. redirect to home page
					return RedirectToAction("Index", "HomePage");
				}
				else
				{
					// Do something on failure, e.g. show error message
					ModelState.AddModelError("", "Invalid email or password");
				}
			}

			return View(model);
		}
		[HttpGet]
		public IActionResult Register()
		{
			return View();
		}
		[HttpPost]
		public async Task<IActionResult> Register(UserRegisterDto model)
		{
			if (ModelState.IsValid)
			{
				var content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");

				using var response = await _httpClient.PostAsync($"{_baseUrl}/User/Register/Register", content);

				if (response.IsSuccessStatusCode)
				{
					// Do something on success, e.g. redirect to login page
					return RedirectToAction("Login");
				}
				else
				{
					// Do something on failure, e.g. show error message
					ModelState.AddModelError("", "Registration failed");
				}
			}

			return View(model);
		}
	}
}

src/Presentation/BiletAPI.WebUI/Views/City/AddCity.cshtml
@model CityDto
@{
    ViewData["Title"] = "Şehir ekle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 style="text-align:center">Şehir Ekle</h1>
<form asp-action="AddCity" asp-controller="City" style="display:flex; justify-content:center; align-items:center;">
		<div class="input-box">
			<input asp-for="CityName" type="text" placeholder="Şehrin Adını Giriniz" required>
			<span asp-validation-for="CityName" class="text-danger" style="margin-left:15px; font-size:12px;"></span>
		</div>
		<div class="input-box button">
			<input type="Submit" value="+ Ekle">
		</div>
	</form>

src/Presentation/BiletAPI.WebUI/Views/Login/Login.cshtml
@model LoginDto
@{
    Layout = null;
}



<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title> Kayıt Ol </title>
	<link rel="stylesheet" href="/SignupForm/style.css">
</head>
<body>
	<div class="wrapper">
		<h2>Giriş Yap</h2>
		<form asp-action="Login" asp-controller="Login">
			<div class="input-box">
				<input asp-for="Mail" type="email" placeholder="Mailinizi Giriniz" required>
				<span asp-validation-for="Mail" class="text-danger" style="margin-left:15px; font-size:12px;"></span>
			</div>
			<div class="input-box">
				<input asp-for="Password" type="password" placeholder="Şifrenizi Giriniz" required>
				<span asp-validation-for="Password" class="text-danger" style="margin-left:15px; font-size:12px;"></span>
			</div>
			<div class="input-box button">
				<input type="Submit" value="Giriş Yap">
			</div>
			<div class="text">
				<h3>Kayıtlı değil misiniz? <a href="/Login/Register/">Şimdi Kayıt Ol</a></h3>
			</div>
		</form>
	</div>

</body>
</html>

src/Presentation/BiletAPI.WebUI/Views/Login/Register.cshtml
@model UserRegisterDto
@{
	Layout = null;
}


<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title> Kayıt Ol </title>
	<link rel="stylesheet" href="/SignupForm/style.css">
</head>
<body>
	<div class="wrapper">
		<h2>Kayıt Ol</h2>
		<form asp-action="Register" asp-controller="Login">
			<div class="input-box">
				<input asp-for="Name" type="text" placeholder="İsim Giriniz" required>
				<span asp-validation-for="Name" class="text-danger" style="margin-left:15px; font-size:12px;"></span>
			</div>
			<div class="input-box">
				<input asp-for="Surname" type="text" placeholder="Soyisim Giriniz" required>
				<span asp-validation-for="Surname" class="text-danger" style="margin-left:15px; font-size:12px;"></span>
			</div>
			<div class="input-box">
				<input asp-for="Age" type="number" placeholder="Yaşınızı Giriniz" required>
				<span asp-validation-for="Age" class="text-danger" style="margin-left:15px; font-size:12px;"></span>
			</div>
			<div class="text" style="display:flex; align-items:center">
				<label asp-for="Gender">Cinsiyetinizi seçiniz :</label>
				<div class="radio-buttons" style="display:flex; margin-inline:10px ; align-items:center; ">
					Kadın	<input style="margin-inline:10px" type="radio" asp-for="Gender" value="false">
					Erkek	<input style="margin-inline:10px" type="radio" asp-for="Gender" value="true">
				</div>
			</div>
			<div class="input-box">
				<input asp-for="Mail" type="email" placeholder="Mailinizi Giriniz" required>
				<span asp-validation-for="Mail" class="text-danger" style="margin-left:15px; font-size:12px;"></span>
			</div>
			<div class="input-box">
				<input asp-for="PhoneNumber" type="number" placeholder="Telefon Numaranızı Giriniz" required>
				<span asp-validation-for="PhoneNumber" class="text-danger" style="margin-left:15px; font-size:12px;"></span>
			</div>
			<div class="input-box">
				<input asp-for="Password" type="password" placeholder="Şifrenizi Giriniz" required>
				<span asp-validation-for="Password" class="text-danger" style="margin-left:15px; font-size:12px;"></span>
			</div>
			<div class="input-box button">
				<input type="Submit" value="Şimdi Kayıt Ol">
			</div>
			<div class="text">
				<h3>Kayıtlı mısınız? <a href="/Login/Login/">Giriş Yap</a></h3>
			</div>
		</form>
	</div>

</body>
</html>

src/Presentation/BiletAPI.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Anasayfa</title>

	<!-- Custom fonts for this template-->
	<link href="~/startbootstrap-sb-admin-2-gh-pages/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
		  rel="stylesheet">

	<!-- Custom styles for this template-->
	<link href="~/startbootstrap-sb-admin-2-gh-pages/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

	<!-- Page Wrapper -->
	<div id="wrapper">

		<!-- Sidebar -->
		<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

			<!-- Sidebar - Brand -->
			<a class="sidebar-brand d-flex align-items-center justify-content-center">
				<div class="sidebar-brand-icon rotate-n-15">
					<i class="fas fa-laugh-wink"></i>
				</div>
				<div class="sidebar-brand-text mx-3">Ucuz <sup>bilet</sup>AL </div>
			</a>

			<!-- Divider -->
			<hr class="sidebar-divider my-0">

			<!-- Nav Item - Dashboard -->
			<li class="nav-item active">
				<a class="nav-link" href="index.html">
					<i class="fas fa-fw fa-tachometer-alt"></i>
					<span>Sefer Ekle</span>
				</a>
			</li>
			<li class="nav-item active">
				<a class="nav-link" href="index.html">
					<i class="fas fa-fw fa-tachometer-alt"></i>
					<span>Sefer Listesi</span>
				</a>
			</li>
			<li class="nav-item active">
				<a class="nav-link" href="/City/AddCity/">
					<i class="fas fa-fw fa-tachometer-alt"></i>
					<span>Şehir Ekle</span>
				</a>
			</li>
		</ul>
		<!-- End of Sidebar -->
		<!-- Content Wrapper -->
		<div id="content-wrapper" class="d-flex flex-column">

			<!-- Main Content -->
			<div id="content">

				<!-- Topbar -->
				<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
					<ul>
						<!-- Sidebar Toggle (Topbar) -->
						<li class ="nav-item dropdown no-arrow" >
							<button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
							</button>
							<i class="fa fa-bars"></i>
						</li>
						
						<li class="nav-item dropdown no-arrow">
							<a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
							   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<span class="mr-2 d-none d-lg-inline text-gray-600 small">@ViewBag.KullaniciAdi</span>
								<img class="img-profile rounded-circle"
		  src="~/startbootstrap-sb-admin-2-gh-pages/img/undraw_profile.svg">
							</a>
							<!-- Dropdown - User Information -->
							<div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
								 aria-labelledby="userDropdown">
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
									<i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
									Logout
								</a>
							</div>
						</li>
						
					</ul>

				</nav>
				@RenderBody()
			</div>
			<!-- End of Main Content -->
			<!-- Footer -->
			<footer class="sticky-footer bg-white">
				<div class="container my-auto">
					<div class="copyright text-center my-auto">
						<span>Copyright &copy; Your Website 2021</span>
					</div>
				</div>
			</footer>
			<!-- End of Footer -->
		</div>
		<!-- End of Content Wrapper -->
	</div>
	<!-- End of Page Wrapper -->
	<!-- Scroll to Top Button-->
	<a class="scroll-to-top rounded" href="#page-top">
		<i class="fas fa-angle-up"></i>
	</a>

	<!-- Logout Modal-->
	<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
		 aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
					<button class="close" type="button" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">×</span>
					</button>
				</div>
				<div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
				<div class="modal-footer">
					<button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
					<a class="btn btn-primary" href="login.html">Logout</a>
				</div>
			</div>
		</div>
	</div>

	<!-- Bootstrap core JavaScript-->
	<script src="~/startbootstrap-sb-admin-2-gh-pages/vendor/jquery/jquery.min.js"></script>
	<script src="~/startbootstrap-sb-admin-2-gh-pages/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

	<!-- Core plugin JavaScript-->
	<script src="~/startbootstrap-sb-admin-2-gh-pages/vendor/jquery-easing/jquery.easing.min.js"></script>

	<!-- Custom scripts for all pages-->
	<script src="~/startbootstrap-sb-admin-2-gh-pages/js/sb-admin-2.min.js"></script>

	<!-- Page level plugins -->
	<script src="~/startbootstrap-sb-admin-2-gh-pages/vendor/chart.js/Chart.min.js"></script>

	<!-- Page level custom scripts -->
	<script src="~/startbootstrap-sb-admin-2-gh-pages/js/demo/chart-area-demo.js"></script>
	<script src="~/startbootstrap-sb-admin-2-gh-pages/js/demo/chart-pie-demo.js"></script>

</body>

</html>